## Rss2Snb Config File
## 请注意缩进，不要使用Tab，全部用空格。
## 注：各平台均使用默认字符集，Windows请使用GBK，Ubuntu请使用UTF-8（别改就是了）

# 通用设置
general:
  # 临时目录路径
  temp: d:/rss2snb/target
  # 生成的最终snb文件路径
  target: d:/rss2snb/rss.snb
  # 是否自动上传至BamBook
  auto_upload: true
  # BamBook地址，如用USB连接，默认为192.168.250.2；如用WIFI，请指定其他IP
  bb_address: 192.168.250.2

# HTTP代理服务器配置，以下四项，如没有则留空
proxy:
  proxy_host: 127.0.0.1
  proxy_port: 8580
  proxy_user: 
  proxy_password: 

## =====================================================
## 以下内容如无必要，无需修改
## =====================================================

# 电子书信息
book:
  # 书名
  name: RSS电子书
  # 作者
  author: Rss2Snb
  # 语言，如无必要，请勿修改
  language: zh-CN
  # 版权信息
  copyright: 所有版权归原作者所有，本书由Rss2Snb生成。
  # 摘要
  abstract: 由Rss2Snb根据指定RSS生成的电子书。

# 内容抓取插件配置
plugins:
    # 具体Feed项的链接前缀，此处为InfoQ插件的前缀
  - url_prefix: http://www.infoq.com
    # 针对该链接的插件类名
    plugin: Rss::Plugin::InfoQ

    # 以下插件对应的网站RSS是http://blog.nosqlfan.com
  - url_prefix: http://blog.nosqlfan.com/html
    plugin: Rss::Plugin::NosqlFan

    # 以下插件对应的网站RSS是http://feeds.feedburner.com/HighScalability ，该RSS需要代理访问
  - url_prefix: http://feedproxy.google.com/~r/HighScalability
    plugin: Rss::Plugin::HighScalability

    # 以下插件对应的网站RSS是http://feeds.feedburner.com/nosql ，该RSS需要代理访问
  - url_prefix: http://feedproxy.google.com/~r/nosql
    plugin: Rss::Plugin::MyNoSql

    # 以下插件对应的网站RSS是http://feeds.feedburner.com/arch ，该RSS需要代理访问
  - url_prefix: http://feedproxy.google.com/~r/arch
    plugin: Rss::Plugin::ScalableWebArchitectures

    # 以下插件对应的网站RSS是http://feeds.feedburner.com/SpringSourceTeamBlog ，该RSS需要代理访问
  - url_prefix: http://feedproxy.google.com/~r/SpringSourceTeamBlog
    plugin: Rss::Plugin::SpringsourceTeamBlog
